use crate::config;
use crate::error::{Error, Result};
use crate::tui;
use std::fs;
use std::path::Path;

/// `qvm init` — first-run setup.
///
/// Defaults to the TUI onboarding wizard (same UX as bare `qvm` on a fresh
/// host). `--yes` writes a default config without prompting, for automation.
/// `--force` overwrites an existing config.
pub fn run(config_path: &Path, yes: bool, force: bool) -> Result<()> {
    if config_path.exists() && !force {
        return Err(Error::User(format!(
            "config already exists at {}\n  - edit it directly, or\n  - rerun with --force to redo setup, or\n  - delete the file and rerun `qvm init`.",
            config_path.display()
        )));
    }

    if yes {
        write_defaults(config_path)?;
    } else if let Err(e) = tui::onboard::run(config_path) {
        return Err(Error::User(format!(
            "onboarding failed: {e}\n  - rerun with --yes to write defaults non-interactively."
        )));
    }

    // Whether the TUI or --yes wrote the config, ensure dirs are present
    // so the very next `qvm run` doesn't trip on a missing /var/lib/qvm.
    let cfg = config::Config::load(Some(config_path))?;
    cfg.ensure_dirs()?;
    Ok(())
}

fn write_defaults(config_path: &Path) -> Result<()> {
    if let Some(parent) = config_path.parent() { fs::create_dir_all(parent)?; }
    fs::write(config_path, config::sample_toml())?;
    println!("Wrote default config to {}", config_path.display());
    Ok(())
}

// ── shared by TUI onboarding (`src/tui/onboard.rs`) ──────────────────────────

pub struct WizardAnswers<'a> {
    pub bridge:         &'a str,
    pub distro:         &'a str,
    pub cpus:           u32,
    pub memory_gb:      u32,
    pub disk_gb:        u32,
    pub autostart:      bool,
    pub grub_timeout:   u32,
    pub vnc_bind:       &'a str,
    pub ssh_keys:       &'a [String],
    pub images_path:    &'a str,
    pub vms_path:       &'a str,
    pub cloudinit_path: &'a str,
}

/// Render the final `/etc/qvm/config.toml`. Exposed so the TUI onboarding
/// wizard (`src/tui/onboard.rs`) writes the same TOML as `qvm init`.
pub fn render_config(a: WizardAnswers<'_>) -> String {
    let keys_toml = if a.ssh_keys.is_empty() {
        "    # \"ssh-ed25519 AAAA... you@host\",\n".to_string()
    } else {
        a.ssh_keys.iter()
            .map(|k| format!("    \"{}\",\n", toml_escape(k)))
            .collect()
    };

    let autostart_str = if a.autostart { "true" } else { "false" };

    format!(
"# qvm configuration — generated by `qvm init`.
# Edit freely; all fields are optional (baked-in defaults apply if omitted).

# SSH public keys injected for the login user and root on every new VM.
# IMPORTANT: this is a top-level key — it MUST stay above every [section]
# header below, otherwise TOML parses it as part of the preceding table.
ssh_keys = [
{keys}]

[paths]
images    = \"{images}\"
vms       = \"{vms}\"
cloudinit = \"{ci}\"

[network]
bridge = \"{bridge}\"

[defaults]
distro       = \"{distro}\"
cpus         = {cpus}
memory_gb    = {mem}
disk_gb      = {disk}
autostart    = {autostart}
# 0 = instant boot. Comment out the line to keep the distro default.
grub_timeout = {grub}

# Username and password are required per-VM at create time; qvm has no
# default for either. Pass them on the CLI (`-u`/`-p`) or in the TUI
# Create form.

[vnc]
bind = \"{vnc}\"

[tui]
theme = \"mocha\"  # \"mocha\" (dark, default) or \"latte\" (light)

# ── Custom distros (optional) ────────────────────────────────────────────────
# Add or override built-in distros. Built-ins:
#   ubuntu:24.04   debian:13   fedora:42   alpine:3.20   rocky:9
#
# [distros.\"ubuntu:22.04\"]
# image  = \"ubuntu-22.04.qcow2\"
# osinfo = \"ubuntu22.04\"
# shell  = \"/bin/bash\"
# uefi   = false
# url    = \"https://cloud-images.ubuntu.com/releases/jammy/release/ubuntu-22.04-server-cloudimg-amd64.img\"
",
        images  = toml_escape(a.images_path),
        vms     = toml_escape(a.vms_path),
        ci      = toml_escape(a.cloudinit_path),
        bridge  = toml_escape(a.bridge),
        distro  = toml_escape(a.distro),
        cpus    = a.cpus,
        mem     = a.memory_gb,
        disk    = a.disk_gb,
        autostart = autostart_str,
        grub    = a.grub_timeout,
        vnc     = toml_escape(a.vnc_bind),
        keys    = keys_toml,
    )
}

/// Escape a string for use inside a TOML basic (double-quoted) string.
pub fn toml_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"'  => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04X}", c as u32));
            }
            c => out.push(c),
        }
    }
    out
}
