//! cloud-init seed generation.
//!
//! We emit a single user-data that:
//!   * creates the login user + root with SSH keys and password
//!   * installs and enables qemu-guest-agent (generic across init systems)
//!   * configures GRUB timeout (default 0 = instant boot)
//!
//! All cross-distro behaviour is in a small first-boot script that
//! feature-detects systemctl vs rc-update etc. - NO per-distro branching here.

use crate::cmd::{require, run};
use crate::config::Config;
use crate::error::Result;
use std::fs;
use std::path::{Path, PathBuf};

pub struct Seed<'a> {
    pub vm_name:      &'a str,
    pub login_user:   &'a str,
    pub login_shell:  &'a str,
    pub password_hash:&'a str,
    pub ssh_keys:     &'a [String],
    pub grub_timeout: Option<u32>,
}

impl<'a> Seed<'a> {
    /// Write user-data + meta-data + .vmuser sidecar into `ci_dir`.
    /// Does not require genisoimage; usable in tests and as a recovery point
    /// if the ISO step later fails.
    pub fn write_files(&self, ci_dir: &Path) -> Result<()> {
        fs::create_dir_all(ci_dir)?;
        fs::write(ci_dir.join(".vmuser"), format!("{}\n", self.login_user))?;
        fs::write(ci_dir.join("user-data"), self.user_data())?;
        fs::write(ci_dir.join("meta-data"), format!(
            "instance-id: {0}\nlocal-hostname: {0}\n", self.vm_name
        ))?;
        Ok(())
    }

    /// Build the seed ISO from files already in `ci_dir`. Requires genisoimage.
    pub fn build_iso(&self, ci_dir: &Path, iso_path: &Path) -> Result<()> {
        require("genisoimage")?;
        run("genisoimage", [
            "-quiet", "-output", iso_path.to_str().unwrap(),
            "-volid", "cidata", "-joliet", "-rock",
            ci_dir.join("user-data").to_str().unwrap(),
            ci_dir.join("meta-data").to_str().unwrap(),
        ])?;
        Ok(())
    }

    /// Convenience: write files + build the ISO in one step. Returns the
    /// ISO path. This is what create_vm calls in normal operation.
    pub fn build(&self, ci_dir: &Path, iso_path: &Path) -> Result<PathBuf> {
        self.write_files(ci_dir)?;
        self.build_iso(ci_dir, iso_path)?;
        Ok(iso_path.to_path_buf())
    }

    fn user_data(&self) -> String {
        let mut keys_yaml = String::new();
        for k in self.ssh_keys {
            keys_yaml.push_str(&format!("      - {k}\n"));
        }

        let firstboot = firstboot_script(self.grub_timeout);
        // Indent the script body by 6 spaces for the YAML block scalar.
        let firstboot_indented: String = firstboot
            .lines()
            .map(|l| format!("      {l}"))
            .collect::<Vec<_>>()
            .join("\n");

        format!(
"#cloud-config
hostname: {name}
manage_etc_hosts: true
ssh_pwauth: true
packages: [qemu-guest-agent]
users:
  - name: {user}
    groups: sudo
    shell: {shell}
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: \"{pw}\"
    ssh-authorized-keys:
{keys}  - name: root
    ssh-authorized-keys:
{keys}write_files:
  - path: /opt/qvm-firstboot.sh
    permissions: '0755'
    content: |
{firstboot}
runcmd:
  - /opt/qvm-firstboot.sh
",
            name = self.vm_name,
            user = self.login_user,
            shell = self.login_shell,
            pw = self.password_hash,
            keys = if keys_yaml.is_empty() { "      []\n".to_string() } else { keys_yaml },
            firstboot = firstboot_indented,
        )
    }
}

/// Generic first-boot script. Feature-detects rather than per-distro branches.
fn firstboot_script(grub_timeout: Option<u32>) -> String {
    let t = grub_timeout.map(|n| n.to_string()).unwrap_or_default();
    format!(r#"#!/bin/sh
# Generated by qvm - runs once on first boot.

# --- GRUB timeout (best-effort across distros) ---
T="{t}"
if [ -n "$T" ]; then
    if [ -f /etc/default/grub ] && grep -q '^GRUB_TIMEOUT=' /etc/default/grub; then
        sed -i "s/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT=$T/" /etc/default/grub
    else
        echo "GRUB_TIMEOUT=$T" >> /etc/default/grub
    fi
    if command -v update-grub >/dev/null 2>&1; then update-grub || true
    elif command -v grub2-mkconfig >/dev/null 2>&1; then
        [ -d /boot/grub2 ] && grub2-mkconfig -o /boot/grub2/grub.cfg || grub2-mkconfig -o /boot/grub/grub.cfg || true
    elif command -v grub-mkconfig >/dev/null 2>&1; then
        grub-mkconfig -o /boot/grub/grub.cfg || true
    fi
fi

# --- qemu-guest-agent: systemd OR openrc ---
if command -v systemctl >/dev/null 2>&1; then
    systemctl enable --now qemu-guest-agent || true
elif command -v rc-update >/dev/null 2>&1; then
    rc-update add qemu-guest-agent default || true
    rc-service qemu-guest-agent start || true
fi
"#)
}

/// Read back the persisted login user for a VM (None if missing/unreadable).
pub fn login_user_of(cfg: &Config, vm: &str) -> Option<String> {
    let p = cfg.paths.cloudinit.join(vm).join(".vmuser");
    fs::read_to_string(p).ok().and_then(|s| {
        let line = s.lines().next()?.trim().to_string();
        if line.is_empty() { None } else { Some(line) }
    })
}
